export type PPL_Constants = {
	HARVEST_INDEX: number;
	AERIAL_RESIDUE_INDEX: number;
	PRODUCT_RESIDUE_INDEX: number;
	PRODUCT_DRY_MATTER_FACTOR: number;
	RESIDUE_DRY_MATTER_FACTOR: number;
	BELOWGROUND_INDEX: number;
	WEED_AERIAL_FACTOR: number;
	WEED_BELOWGROUND_INDEX: number;
};
