import "./global.css";
import "react-toastify/dist/ReactToastify.css";

import { Inter } from "next/font/google";
import { Slide, ToastContainer } from "react-toastify";
import AuthProvider from "@/contexts/auth/authContext";
import { Metadata, Viewport } from "next";
import { ConfirmationProvider } from "@/contexts/confirmationModal/confirmationModalContext";

export const metadata: Metadata = {
  title: "Metabolismo Agrário",
  description: "Generated by Next.js",
};

export const viewport: Viewport = {
  initialScale: 0.9,
};

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ConfirmationProvider>
          <AuthProvider>{children}</AuthProvider>
        </ConfirmationProvider>
        <ToastContainer
          position="top-center"
          autoClose={1500}
          hideProgressBar={true}
          newestOnTop={false}
          limit={4}
          closeOnClick
          transition={Slide}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="colored"
        />
      </body>
    </html>
  );
}
