import "./global.css";
import "react-toastify/dist/ReactToastify.css";

import { Inter } from "next/font/google";
import { Slide, ToastContainer } from "react-toastify";
import Head from "next/head";
import AuthProvider from "@/contexts/auth/authContext";

export const metadata = {
	title: "Metabolismo Agrário",
	description: "Generated by Next.js",
};

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<Head>
				<meta name="viewport" content="width=device-width, initial-scale=0.9" />
			</Head>
			<body className={inter.className}>
				<AuthProvider>{children}</AuthProvider>
				<ToastContainer
					position="top-center"
					autoClose={1500}
					hideProgressBar={true}
					newestOnTop={false}
					limit={4}
					closeOnClick
					transition={Slide}
					pauseOnFocusLoss
					draggable
					pauseOnHover
					theme="colored"
				/>
			</body>
		</html>
	);
}
